//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFInalProgramacion3_MatthiasPaniagua.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarios
    {
        public int SalariosId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<double> salario { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
